### ISSUE TITLE
Fails in npm install

### ISSUE THREAD

**Issue by yuta-imai** [momentohq/client-sdk-examples#35]
Hi, I am trying to install javascript sdk with npm command, and running into the issue below.

```
% npm config set @momento:registry https://momento.jfrog.io/artifactory/npm-public/
% npm install @momento/sdk
npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://momento.jfrog.io/artifactory/npm-public/@momento%2fsdk/ reason: Unexpected token < in JSON at position 0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-12-29T04_56_28_944Z-debug.log
```

For work around, I have succeeded to install it with downloading package from jfrog and installing from local file system with npm command.

**Comment by danielamiao** [comment]
@yuta-imai Thank you very much for reporting this! We found a typo in our instructions, sorry about that. The fix is merged now.
