### ISSUE TITLE
I suggest adding .NET dependencies in the public nuget.

### ISSUE THREAD

**Issue by ramonduraes** [momentohq/client-sdk-examples#87]
I suggest adding .NET dependencies in the public nuget.
https://www.nuget.org

**Comment by kvcache** [comment]
Hi @ramonduraes, thank you for opening this issue! We agree & it's on our radar.

**Comment by pgautier404** [comment]
.NET dependencies are available on NuGet! 
https://www.nuget.org/profiles/Momento
