### ISSUE TITLE
Set up dependabot on this repo so we get latest SDK updates faster

### ISSUE THREAD

**Issue by eaddingtonwhite** [momentohq/client-sdk-examples#99]
This can be tackled one language at a time.  For each language:

* Add dependabot config so that it will file a PR when there is a new momento SDK release.  (Do we want to filter out other deps and only configure dependabot for the mmomento dep?)
* When the PR is file, needs to trigger some CI action that at least attempts to build/lint the example code, to ensure that the binary package was valid.
* If the validation fails then we need to notify in some very visible way... send a message to slack channel? cut a ticket and add it to the project board?  something that really ensures it will get our attention.
* In the future it would be nice to validate beyond just building; e.g. actually run the example code.  For now that would require a token though, may not be a good idea until we have a way to run tests against e.g. momento local docker container.

We need to get this done for at least these languages:

- [ ] javascript
- [ ] python
- [ ] c# (shouldn't tackle this until we've moved publishing to nuget)
- [ ] java (shouldn't tackle this until we've moved publishing to maven central)

**Comment by pgautier404** [comment]
Followup issues have been added for enhanced notification beyond the current email (#110) and for adding end-to-end testing for languages that currently lack it (#111).
